resources:
- pipeline-build.yaml
- pipeline-security-checks.yaml
- pipeline-change-test.yaml
- pipeline-change-prod.yaml

- pvc-workspace.yaml
- sa-pipeline.yaml
- configmap-argocd-env.yaml

- sealed-secret-allure.yaml
- sealed-secret-github-deployment.yaml
- sealed-secret-quay.yaml
- sealed-secret-roxsecrets.yaml
- sealed-secret-sonarcloud.yaml
- sealed-secret-argocd-env-secret.yaml
- sealed-secret-smtp-creds.yaml

- task-git-update-deployment.yaml
- task-sonarqube-scanner.yaml
- task-zap-proxy.yaml
- task-rox-deployment-check-remote.yaml  
- task-rox-image-check.yaml  
- task-rox-image-scan.yaml 
- task-argocd-task-sync-and-wait.yaml
- task-sendmail.yaml

